FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates curl wget git sudo tmux vim less jq ripgrep unzip zip \
      build-essential python3 python3-venv pkg-config procps locales \
      openssh-client gnupg2 zsh \
    && rm -rf /var/lib/apt/lists/* \
    && locale-gen en_US.UTF-8
ARG USER=coder
RUN useradd --groups sudo --create-home --shell /bin/bash ${USER} \
    && echo "${USER} ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/${USER} \
    && chmod 0440 /etc/sudoers.d/${USER}
USER ${USER}
ENV LANG=en_US.UTF-8
WORKDIR /home/${USER}
