#!/usr/bin/env bash
# Runs install.sh in a container that mimics a dsp-base workspace.
#
#   ./tests/run.sh          fresh volume, install, assert, simulate restart, assert again
#   ./tests/run.sh --keep   reuse the existing volume (faster iteration)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
IMAGE=dotfiles-test
VOLUME=dotfiles-test-home
# shellcheck source=tests/lib.sh
source "$HERE/lib.sh"

case "${1:-}" in
  ""|--keep) ;;
  *) echo "run.sh: unknown argument: $1" >&2; exit 2 ;;
esac
[ "${1:-}" = "--keep" ] || podman volume rm -f "$VOLUME" >/dev/null 2>&1 || true
podman volume create "$VOLUME" >/dev/null 2>&1 || true
podman build -q -t "$IMAGE" -f "$HERE/Containerfile" "$HERE" >/dev/null

# Each invocation is a NEW container on the SAME volume: /usr resets, $HOME persists.
in_workspace() {
  # The GIT_* values mimic what the Coder agent exports. They are deliberately
  # WRONG so the identity assertions actually prove .zshenv/.bashrc beat them;
  # without these the test would pass even if the unset were missing entirely.
  podman run --rm -i \
    -v "$VOLUME:/home/coder" \
    -v "$REPO:/repo:ro" \
    -e CODER_AGENT_URL=http://fake.invalid \
    -e GIT_AUTHOR_NAME="Wrong Person" \
    -e GIT_AUTHOR_EMAIL=wrong@example.com \
    -e GIT_COMMITTER_NAME="Wrong Person" \
    -e GIT_COMMITTER_EMAIL=wrong@example.com \
    "$IMAGE" bash -s
}

install_run() {
  in_workspace <<'SH'
set -e
# Reproduce what `coder dotfiles` does: clone into Coder's global config dir.
mkdir -p ~/.config/coderv2
rm -rf ~/.config/coderv2/dotfiles
cp -r /repo ~/.config/coderv2/dotfiles
# Measured right after the clone, before install.sh runs: catches install.sh
# (or anything it runs, like `:Lazy update`) writing INTO the clone. A flat
# zero would false-fail on a host with an in-progress edit to install.sh, so
# we compare this against the same measurement taken after install.sh below.
REPO_STATUS_BEFORE="$(git -C ~/.config/coderv2/dotfiles status --porcelain | wc -l)"
chmod +x ~/.config/coderv2/dotfiles/install.sh
# Seed a real pre-existing file so the backup-before-overwrite path is
# actually exercised; on a fresh volume ~/.zshrc doesn't exist yet, so
# without this the backup logic would go untested. Idempotent: on the
# second run ~/.zshrc is already install.sh's symlink, so this leaves it
# alone.
[ -e ~/.zshrc ] || echo '# pre-existing user file' > ~/.zshrc
~/.config/coderv2/dotfiles/install.sh
REPO_STATUS_AFTER="$(git -C ~/.config/coderv2/dotfiles status --porcelain | wc -l)"
echo "repo_status_delta=$((REPO_STATUS_AFTER - REPO_STATUS_BEFORE))"
SH
}

echo "=== first install (fresh home) ==="
FIRST="$(install_run 2>&1)" || { echo "$FIRST"; echo "install failed"; exit 1; }
echo "$FIRST" | tail -20

echo
echo "=== assertions after first install ==="
CHECKS="$(in_workspace <<'SH'
export PATH="$HOME/.local/bin:$PATH"
echo "nvim=$(command -v nvim || echo none)"
echo "difft=$(command -v difft || echo none)"
echo "fastfetch=$(command -v fastfetch || echo none)"
echo "herdr=$(command -v herdr || echo none)"
echo "zshrc=$(readlink -f ~/.zshrc || echo none)"
echo "nvimcfg=$(readlink -f ~/.config/nvim || echo none)"
echo "gitconfig_first_line=$(head -1 ~/.gitconfig 2>/dev/null)"
echo "git_email=$(git config --get user.email)"
echo "zsh_ident=$(zsh -ic 'git var GIT_AUTHOR_IDENT' 2>/dev/null | tail -1)"
echo "bash_ident=$(bash -lc 'git var GIT_AUTHOR_IDENT' 2>/dev/null | tail -1)"
echo "shell=$(getent passwd coder | cut -d: -f7)"
echo "backups=$(ls -d ~/*.pre-dotfiles* 2>/dev/null | wc -l)"
SH
)"
echo "$CHECKS"

assert_not_contains "nvim installed"      "nvim=none"      "$CHECKS"
assert_not_contains "difftastic installed" "difft=none"    "$CHECKS"
assert_not_contains "fastfetch installed" "fastfetch=none" "$CHECKS"
assert_not_contains "herdr installed"     "herdr=none"     "$CHECKS"
assert_contains "nvim is under ~/.local"  "nvim=/home/coder/.local/bin/nvim" "$CHECKS"
assert_contains "gitconfig is generated"  "gitconfig_first_line=# generated by dotfiles install.sh" "$CHECKS"
assert_contains "zsh identity beats the agent env" \
  "zsh_ident=Richard Garber <9834847+rgarber11@users.noreply.github.com>" "$CHECKS"
assert_contains "bash identity beats the agent env" \
  "bash_ident=Richard Garber <9834847+rgarber11@users.noreply.github.com>" "$CHECKS"
assert_not_contains "the wrong address never wins" "wrong@example.com" "$CHECKS"
assert_contains "login shell is zsh"      "shell=/usr/bin/zsh" "$CHECKS"
assert_contains "zshrc symlinks into the repo" \
  "zshrc=/home/coder/.config/coderv2/dotfiles/headless/zshrc" "$CHECKS"
assert_contains "nvim config symlinks into the repo" \
  "nvimcfg=/home/coder/.config/coderv2/dotfiles/shared/nvim" "$CHECKS"
assert_contains "pre-existing zshrc was backed up, not clobbered" "backups=1" "$CHECKS"
assert_contains "install.sh does not modify the dotfiles clone" "repo_status_delta=0" "$FIRST"

echo
echo "=== second install (new container, same home: simulates restart) ==="
SECOND="$(install_run 2>&1)" || { echo "$SECOND"; echo "second install failed"; exit 1; }
echo "$SECOND" | tail -20

echo
echo "=== assertions after restart ==="
assert_not_contains "neovim not re-downloaded"    "downloading nvim"      "$SECOND"
assert_not_contains "difftastic not re-downloaded" "downloading difft"     "$SECOND"
assert_not_contains "fastfetch not re-downloaded" "downloading fastfetch" "$SECOND"
assert_not_contains "herdr not reinstalled"       "installing herdr"      "$SECOND"
assert_contains "install.sh does not modify the dotfiles clone (restart)" "repo_status_delta=0" "$SECOND"

AFTER="$(in_workspace <<'SH'
export PATH="$HOME/.local/bin:$PATH"
echo "nvim=$(command -v nvim || echo none)"
echo "shell=$(getent passwd coder | cut -d: -f7)"
echo "zshrc=$(readlink -f ~/.zshrc || echo none)"
echo "nvimcfg=$(readlink -f ~/.config/nvim || echo none)"
echo "backups=$(ls -d ~/*.pre-dotfiles* 2>/dev/null | wc -l)"
echo "bashrc_blocks=$(grep -cF '# >>> dotfiles: coder git identity >>>' ~/.bashrc)"
echo "profile_blocks=$(grep -cF '# >>> dotfiles: coder git identity >>>' ~/.profile)"
SH
)"
echo "$AFTER"
assert_contains "nvim survived the restart" "nvim=/home/coder/.local/bin/nvim" "$AFTER"
assert_contains "chsh re-applied after restart" "shell=/usr/bin/zsh" "$AFTER"
assert_contains "zshrc symlink survived the restart" \
  "zshrc=/home/coder/.config/coderv2/dotfiles/headless/zshrc" "$AFTER"
assert_contains "nvim config symlink survived the restart" \
  "nvimcfg=/home/coder/.config/coderv2/dotfiles/shared/nvim" "$AFTER"
assert_contains "no duplicate backup on restart" "backups=1" "$AFTER"
assert_contains "no duplicate bashrc block" "bashrc_blocks=1" "$AFTER"
assert_contains "no duplicate profile block" "profile_blocks=1" "$AFTER"

summary
