#!/usr/bin/env bash
# ~/.gitconfig is GENERATED, never symlinked. The template's startup script runs
# `git config --global credential.helper store`; against a symlink that write
# would land inside the tracked repo, leaving it permanently dirty and in
# conflict with the next `coder dotfiles` pull.
#
# Regenerated only when the marker is missing, so anything the template appends
# survives restarts -- the same trick the template uses for ~/.aws/config.

GITCONFIG="$HOME/.gitconfig"
MARKER="# generated by dotfiles install.sh"

if [ ! -f "$GITCONFIG" ] || ! head -1 "$GITCONFIG" | grep -qF "$MARKER"; then
  if [ -f "$GITCONFIG" ]; then
    mv "$GITCONFIG" "$(backup_path "$GITCONFIG")"
    info "backed up pre-existing ~/.gitconfig"
  fi
  cat > "$GITCONFIG" <<EOF
$MARKER -- edit shared/git/common.gitconfig instead
[include]
	path = $HOME/dotfiles/shared/git/common.gitconfig
[include]
	path = $HOME/dotfiles/headless/gitconfig
EOF
  info "generated ~/.gitconfig"
fi

# Git resolves GIT_AUTHOR_*/GIT_COMMITTER_* ahead of user.email, and the Coder
# agent exports them from the account email. ~/.zshenv covers every zsh; these
# blocks cover bash. A process spawned by the agent with no shell in between is
# a known, accepted gap -- see the spec, section 5.
BLOCK_START="# >>> dotfiles: coder git identity >>>"
BLOCK_END="# <<< dotfiles: coder git identity <<<"
for rc in "$HOME/.bashrc" "$HOME/.profile"; do
  [ -f "$rc" ] || touch "$rc"
  if ! grep -qF "$BLOCK_START" "$rc"; then
    cat >> "$rc" <<EOF

$BLOCK_START
unset GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL
$BLOCK_END
EOF
    info "added git identity block to $(basename "$rc")"
  fi
done

# diff.external has no graceful degradation: if difft is missing, git does not
# fall back, it fails every `git diff` outright with "external diff died". Since
# the difftastic step can legitimately fail on a network blip, only enable it
# once the binary is actually there -- and clear it if it ever goes missing, so
# a workspace never ends up unable to diff.
if command -v difft >/dev/null 2>&1; then
  git config --global diff.external difft
else
  git config --global --unset-all diff.external 2>/dev/null || true
  warn "difft not installed; leaving diff.external unset so git diff keeps working"
fi
