#!/usr/bin/env bash
# ~/.gitconfig is GENERATED, never symlinked. The template's startup script runs
# `git config --global credential.helper store`; against a symlink that write
# would land inside the tracked repo, leaving it permanently dirty and in
# conflict with the next `coder dotfiles` pull.
#
# Regenerated only when the marker is missing, so anything the template appends
# survives restarts -- the same trick the template uses for ~/.aws/config.

GITCONFIG="$HOME/.gitconfig"
MARKER="# generated by dotfiles install.sh"

# Both guarded, because unguarded either one aborts the whole install on a
# read-only or full $HOME. What the ordering buys, specifically: the write is
# skipped when the *backup* fails, so a file we could not preserve is never
# overwritten -- it stays untouched at the canonical path. The other direction
# (backup succeeds, write fails) still leaves no ~/.gitconfig, and cannot be
# closed by ordering alone; the content is recoverable at the .pre-dotfiles path
# and git falls back to its defaults meanwhile, which is why a warn is enough.
if [ ! -f "$GITCONFIG" ] || ! head -1 "$GITCONFIG" | grep -qF "$MARKER"; then
  gitconfig_ready=1
  if [ -f "$GITCONFIG" ]; then
    if mv "$GITCONFIG" "$(backup_path "$GITCONFIG")"; then
      info "backed up pre-existing ~/.gitconfig"
    else
      gitconfig_ready=0
      warn "could not back up ~/.gitconfig; leaving it alone rather than overwriting it"
    fi
  fi
  if [ "$gitconfig_ready" = 1 ]; then
    if cat > "$GITCONFIG" <<EOF
$MARKER -- edit shared/git/common.gitconfig instead
[include]
	path = $HOME/dotfiles/shared/git/common.gitconfig
[include]
	path = $HOME/dotfiles/headless/gitconfig
EOF
    then
      info "generated ~/.gitconfig"
    else
      warn "could not write ~/.gitconfig; git will fall back to its defaults"
    fi
  fi
fi

# Git resolves GIT_AUTHOR_*/GIT_COMMITTER_* ahead of user.email, and the Coder
# agent exports them from the account email. ~/.zshenv covers every zsh; these
# blocks cover bash. A process spawned by the agent with no shell in between is
# a known, accepted gap -- see the spec, section 5.
BLOCK_START="# >>> dotfiles: coder git identity >>>"
BLOCK_END="# <<< dotfiles: coder git identity <<<"
for rc in "$HOME/.bashrc" "$HOME/.profile"; do
  # `[ -f "$rc" ] || touch "$rc"` put touch on the right of ||, so touch's status
  # became the list's status and an unwritable $HOME aborted the install here.
  if [ ! -f "$rc" ] && ! touch "$rc"; then
    warn "could not create $rc; the agent's git identity will win in bash there"
    continue
  fi
  if ! grep -qF "$BLOCK_START" "$rc"; then
    if cat >> "$rc" <<EOF

$BLOCK_START
unset GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL
$BLOCK_END
EOF
    then
      info "added git identity block to $(basename "$rc")"
    else
      warn "could not append the git identity block to $rc"
    fi
  fi
done

# diff.external has no graceful degradation: if difft is missing, git does not
# fall back, it fails every `git diff` outright with "external diff died". Since
# the difftastic step can legitimately fail on a network blip, only enable it
# once the binary is actually there -- and clear it if it ever goes missing, so
# a workspace never ends up unable to diff.
if command -v difft >/dev/null 2>&1; then
  # Guarded like the --unset-all in the else arm already was: a read-only
  # ~/.gitconfig would otherwise abort the install on this line.
  git config --global diff.external difft ||
    warn "could not set diff.external; git diff will use its built-in differ"
else
  git config --global --unset-all diff.external 2>/dev/null || true
  warn "difft not installed; leaving diff.external unset so git diff keeps working"
fi
