Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add: [bugprone-*, cert-*, modernize-*, performance-*, readability-*]
    Remove:
      [
        bugprone-easily-swappable-parameters,
        modernize-use-trailing-return-type,
        readability-function-cognitive-complexity,
        readability-function-size,
        readability-magic-numbers,
        readability-identifier-length,
        readability-implicit-bool-conversion,
      ]
    CheckOptions:
      readability-braces-around-statements.ShortStatementLines: 1

CompileFlags:
  Add: [-std=c++23]
